// dllmain.h : 模块类的声明。

class CHWCVDLL2Module : public ATL::CAtlDllModuleT< CHWCVDLL2Module >
{
public :
	DECLARE_LIBID(LIBID_HWCVDLL2Lib)
	DECLARE_REGISTRY_APPID_RESOURCEID(IDR_HWCVDLL2, "{4D061C50-9AC8-40B3-97CA-D1EF3B306D8B}")
};

extern class CHWCVDLL2Module _AtlModule;
